name: Flutter CI

on:
    pull_request:
      branches: [ develop, master ]
    
jobs:
#   test_flutter:
#     name: Test Flutter code
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: actions/setup-java@v1
#       with:
#         java-version: '12.x'
#     - uses: subosito/flutter-action@v1
#       with:
#         flutter-version: '1.21.0-9.2.pre'
#         channel: 'beta'
#     - run: flutter pub get
#     - run: flutter test
# TODO: TEST APK TO FIREBASE

  test_android:
    name: Test Android code
    # needs: test_flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: cd
        run: cd android/
      - name: pwd-2
        run: pwd
      - name: ls-1
        run: ls
      - name: Build with Gradle
        run: android/gradlew build
      - name: Run Unit tests
        run: bash android/gradlew test --stacktrace