name: Flutter CI

on:
    pull_request:
      branches: [ develop, master ]
    
jobs:
  unit_test_flutter:
    name: Test Flutter code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.21.0-9.2.pre'
        channel: 'beta'
    - run: flutter pub get
    - run: flutter test
    # TODO: RUN FLUTTER DRIVER TEST

  unit_test_android:
    name: Test Android code
    needs: unit_test_flutter
    runs-on: ubuntu-latest
    # CHECK IF THERE ARE CHANGES IN ANDROID FOLDER
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Need to run Flutter pub get to update local.properties
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.21.0-9.2.pre'
          channel: 'beta'
      - run: flutter pub get
      - name: Make Gradle executable
        working-directory: ./android
        run: chmod +x ./gradlew
      - name: Build with Gradle
        working-directory: ./android
        run: bash ./gradlew build
      - name: Run Unit tests
        working-directory: ./android
        run: bash ./gradlew test --stacktrace